[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docarray>=0.41.0",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.0",
    "pypdf>=6.6.2",
    "python-dotenv>=1.2.1",
]
